[package]
name = "exiftool"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "A wrapper around Phil Harvey's powerful ExifTool."
homepage = "https://github.com/ruurdbijlsma/exiftool"

[dependencies]
serde = { version = "1.0", features = ["derive", "serde_derive"] }
serde_json = { version = "1.0" }
serde_path_to_error = "0.1.17"
thiserror = "2.0.12"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
image = "0.25.6"
walkdir = "2.5.0"
